### ISSUE TITLE
Python 3?

### ISSUE THREAD

**Issue by cdeil** [YSOVAR/YSOVAR#14]
I'm getting this error trying to install with Python 3:
```
hess@lfs1.mpi-hd.mpg.de:~> pip install pYSOVAR
Collecting pYSOVAR
  Downloading pYSOVAR-1.0.tar.gz (54kB)
    100% |████████████████████████████████| 61kB 1.5MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hf3vviil/pYSOVAR/setup.py", line 2, in <module>
        import YSOVAR
      File "/tmp/pip-build-hf3vviil/pYSOVAR/YSOVAR/__init__.py", line 2, in <module>
        import autofuncs
    ImportError: No module named 'autofuncs'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hf3vviil/pYSOVAR/
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Is Python 3 supported yet?
If no, could you please add Python 3 support?

**Comment by hamogu** [comment]
I thought I replied to this issue, but github did not record an answer, so maybe I did not.
First, looking at the error message, I'm no convinced it's due to python 3 and not some other error. However, I;; answer the general "port to python 3?" question here.

We do very little development on this for now and unless there is a one-line fix to make it work, we don't have the time for major changes. The software was written with a specific use case in mind (the YSOVAR project) and although we tried to make it more general, we don't have the capacity to support it indefinitely. There are several other things that could be done better today, e.g. use of new astropy.table.Table features like mix-in columns.

There is still data for the YSOVAR project left and if I will eventually work on these sets, then I'll take the time for a major update, otherwise we'll just fix small bugs as they come.
(We welcome pull requests though, if you want to fix this yourself).
